// <auto-generated />
using System;
using Ecunexo.Billing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Billing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20260821152646_AddInvoiceLineCatalogSnapshot")]
    partial class AddInvoiceLineCatalogSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecunexo.Billing.Core.TaxCatalog.TaxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("RateCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TaxCode", "RateCode", "ValidFrom");

                    b.ToTable("TaxRates", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Core.TaxCatalog.WithholdingRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<string>("RetentionCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TaxType", "RetentionCode", "ValidFrom");

                    b.ToTable("WithholdingRates", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Core.TaxRules.TaxRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Code", "ValidFrom")
                        .IsUnique();

                    b.ToTable("TaxRules", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.ElectronicInvoiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessKey")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)");

                    b.Property<string>("AdditionalNote")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CounterpartyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("EmissionPoint")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("EmitterId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmitterRuc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Establishment")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedDocumentNumber")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("ModifiedDocumentType")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<Guid?>("ModifiedInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ModifiedIssueDate")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PaymentFormCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("01");

                    b.Property<int>("PaymentTermDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Sequential")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("SriMessagesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("SriTransmissionState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("SubtotalWithoutTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TaxTotalsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessKey");

                    b.HasIndex("ModifiedInvoiceId");

                    b.HasIndex("EmitterId", "IssueDate");

                    b.HasIndex("EmitterId", "Establishment", "EmissionPoint", "DocumentType", "Sequential")
                        .IsUnique();

                    b.ToTable("electronic_invoices", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.EmissionPointConfigEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("EmissionPoint")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("EstablishmentId")
                        .HasColumnType("uuid");

                    b.Property<long>("LastSequential")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EstablishmentId", "EmissionPoint", "DocumentType")
                        .IsUnique();

                    b.ToTable("emission_point_configs", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.EmitterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("CertLocation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CertNotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CertNotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CertProvider")
                        .HasColumnType("text");

                    b.Property<string>("CertSecretName")
                        .HasColumnType("text");

                    b.Property<string>("CertSerialNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MainAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TradeName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Ruc");

                    b.HasIndex("TenantId");

                    b.ToTable("emitters", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.EstablishmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("EmitterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmitterId", "Code")
                        .IsUnique();

                    b.ToTable("establishments", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.InvoiceLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemKind")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("LineTotalWithoutTax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MainCode")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("TaxesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId", "LineNumber")
                        .IsUnique();

                    b.ToTable("invoice_lines", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.InvoiceXmlArtifactEntity", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AuthorizationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AuthorizedXml")
                        .HasColumnType("text");

                    b.Property<byte[]>("SignedXml")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("UnsignedXml")
                        .HasColumnType("bytea");

                    b.HasKey("InvoiceId");

                    b.ToTable("invoice_xml_artifacts", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.SriOutboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessKey")
                        .HasMaxLength(49)
                        .HasColumnType("character varying(49)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmitterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("sri_outbox", "billing");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.ElectronicInvoiceEntity", b =>
                {
                    b.HasOne("Ecunexo.Billing.Infrastructure.Persistence.Entities.EmitterEntity", "Emitter")
                        .WithMany()
                        .HasForeignKey("EmitterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Emitter");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.EmissionPointConfigEntity", b =>
                {
                    b.HasOne("Ecunexo.Billing.Infrastructure.Persistence.Entities.EstablishmentEntity", "Establishment")
                        .WithMany("Points")
                        .HasForeignKey("EstablishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Establishment");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.EstablishmentEntity", b =>
                {
                    b.HasOne("Ecunexo.Billing.Infrastructure.Persistence.Entities.EmitterEntity", "Emitter")
                        .WithMany("Establishments")
                        .HasForeignKey("EmitterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emitter");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.InvoiceLineEntity", b =>
                {
                    b.HasOne("Ecunexo.Billing.Infrastructure.Persistence.Entities.ElectronicInvoiceEntity", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.InvoiceXmlArtifactEntity", b =>
                {
                    b.HasOne("Ecunexo.Billing.Infrastructure.Persistence.Entities.ElectronicInvoiceEntity", "Invoice")
                        .WithOne("XmlArtifact")
                        .HasForeignKey("Ecunexo.Billing.Infrastructure.Persistence.Entities.InvoiceXmlArtifactEntity", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.ElectronicInvoiceEntity", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("XmlArtifact");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.EmitterEntity", b =>
                {
                    b.Navigation("Establishments");
                });

            modelBuilder.Entity("Ecunexo.Billing.Infrastructure.Persistence.Entities.EstablishmentEntity", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
